# Interpersonal and Self

```{r}

slc_cr <- read_csv("slc-cr.csv", skip = 1)
colnames(slc_cr) <- c("Progress","Gender","Race","Major_Program","Organization","birth_year","why_take_assessment",paste0("q",seq_along(8:25)))

slc_cr %>% select(q1:q15) %>% cor(use = "p") %>% corrplot()

slc_cr %>% na.omit() -> slc_cr_complete

slc_cr_mod <- "
Civic_Resp =~ q1 + q2 + q3 + q4 + q5 + q6 + q7 + q8 + q9 + q10 + q11 + q12 + q13 + q14 + q15 + q16 + q17 + q18
s1 =~ q1 + q2 + q3 + q4 + q5 + q6 + q7 + q8 + q9
s2 =~ q10 + q11 + q12
s3 =~ q13 + q14 + q15
s4 =~ q16 + q17 + q18
Civic_Resp ~~ 0*s1 + 0*s2 + 0*s3 + 0*s4
Civic_Resp ~~ 1*Civic_Resp
s1 ~~ 0*s2 + 0*s3 + 0*s4
s2 ~~ 0*s3 + 0*s4
s3 ~~ 0*s4
"

sem(slc_cr_mod, data = slc_cr_complete, std.lv = TRUE) %>% {
    fit_cr <<- .
    fitMeasures(., c("cfi","rmsea","srmr"))
    }

semPaths(fit_cr, "std",title = TRUE, curvePivot = TRUE)
title("SLC-CR", line = 3)

```

# Societal

```{r}


slc_cr <- read_csv("slc-cr.csv", skip = 1)
colnames(slc_cr) <- c("Progress","Gender","Race","Major_Program","Organization","birth_year","why_take_assessment",paste0("q",seq_along(8:25)))

slc_cr %>% select(q1:q15) %>% cor(use = "p") %>% corrplot()

slc_cr %>% na.omit() -> slc_cr_complete

slc_cr_mod <- "
Civic_Resp =~ q1 + q2 + q3 + q4 + q5 + q6 + q7 + q8 + q9 + q10 + q11 + q12 + q13 + q14 + q15 + q16 + q17 + q18
s1 =~ q1 + q2 + q3 + q4 + q5 + q6 + q7 + q8 + q9
s2 =~ q10 + q11 + q12
s3 =~ q13 + q14 + q15
s4 =~ q16 + q17 + q18
Civic_Resp ~~ 0*s1 + 0*s2 + 0*s3 + 0*s4
Civic_Resp ~~ 1*Civic_Resp
s1 ~~ 0*s2 + 0*s3 + 0*s4
s2 ~~ 0*s3 + 0*s4
s3 ~~ 0*s4
"

sem(slc_cr_mod, data = slc_cr_complete, std.lv = TRUE) %>% {
    fit_cr <<- .
    fitMeasures(., c("cfi","rmsea","srmr"))
    }

semPaths(fit_cr, "std",title = TRUE, curvePivot = TRUE)
title("SLC-CR", line = 3)

```

# Interpersonal and Group

```{r}

ylc_interpersonal <- read_csv("slc-cr.csv", skip = 1)
colnames(ylc_interpersonal) <- c("Progress","Gender","Race","Major_Program","Organization","birth_year","why_take_assessment",paste0("q",seq_along(8:25)))

ylc_interpersonal %>% select(q1:q15) %>% cor(use = "p") %>% corrplot()

ylc_interpersonal %>% na.omit() -> ylc_interpersonal_complete

ylc_interpersonal_mod <- "
interpersonal =~ q1 + q2 + q3 + q4 + q5 + q6 + q7 + q8 + q9 + q10 + q11 + q12 + q13 + q14 + q15 + q16 + q17 + q18
productive_relationships =~ q1 + q2 + q3 + q4 + q5 + q6 + q7 + q8 + q9
appropriate_interaction =~ q10 + q11 + q12
others_contributions =~ q13 + q14 + q15
verbal_communication =~ q16 + q17 + q18
writing =~ q16 + q17 + q18
conflict_negotiation =~ q16 + q17 + q18
Interpersonal ~~ 0*s1 + 0*s2 + 0*s3 + 0*s4
Interpersonal ~~ 1*Interpersonal
s1 ~~ 0*s2 + 0*s3 + 0*s4
s2 ~~ 0*s3 + 0*s4
s3 ~~ 0*s4
"

sem(ylc_interpersonal_mod, data = slc_cr_complete, std.lv = TRUE) %>% {
    fit_ic <<- .
    fitMeasures(., c("cfi","rmsea","srmr"))
    }

semPaths(fit_cr, "std",title = TRUE, curvePivot = TRUE)
title("SLC-CR", line = 3)

```

# Strategic

```{r}
slc_cr <- read_csv("slc-cr.csv", skip = 1)
colnames(slc_cr) <- c("Progress","Gender","Race","Major_Program","Organization","birth_year","why_take_assessment",paste0("q",seq_along(8:25)))

slc_cr %>% select(q1:q15) %>% cor(use = "p") %>% corrplot()

slc_cr %>% na.omit() -> slc_cr_complete

slc_cr_mod <- "
Civic_Resp =~ q1 + q2 + q3 + q4 + q5 + q6 + q7 + q8 + q9 + q10 + q11 + q12 + q13 + q14 + q15 + q16 + q17 + q18
s1 =~ q1 + q2 + q3 + q4 + q5 + q6 + q7 + q8 + q9
s2 =~ q10 + q11 + q12
s3 =~ q13 + q14 + q15
s4 =~ q16 + q17 + q18
Civic_Resp ~~ 0*s1 + 0*s2 + 0*s3 + 0*s4
Civic_Resp ~~ 1*Civic_Resp
s1 ~~ 0*s2 + 0*s3 + 0*s4
s2 ~~ 0*s3 + 0*s4
s3 ~~ 0*s4
"

sem(slc_cr_mod, data = slc_cr_complete, std.lv = TRUE) %>% {
    fit_cr <<- .
    fitMeasures(., c("cfi","rmsea","srmr"))
    }

semPaths(fit_cr, "std",title = TRUE, curvePivot = TRUE)
title("SLC-CR", line = 3)
6*5/2
```


## Intrapersonal
```{r}
"
self_understanding =~ q9 + q10 + q11
personal_contributions  =~ q15 + q16 + q17
ethics =~ q21 + q22 + q23
confidence =~ q36 + q37 + q38
"
```

## Interpersonal

```{r}

ylc_interpersonal <- read_csv("./data/slc-ii.csv", skip = 1)
ylc_communication <- read_csv("./data/slc-c.csv", skip = 1)

colnames(ylc_interpersonal) <- c("Progress","Gender","Race","Major_Program","Organization","birth_year","why_take_assessment",paste0("q",seq_along(8:40)))
colnames(ylc_communication) <- c("Progress","Gender","Race","Major_Program","Organization","birth_year","why_take_assessment",paste0("q",seq_along(8:29)))


ylc_interpersonal %>% na.omit() -> ylc_interpersonal_complete
ylc_communication %>% na.omit() -> ylc_communication_complete


full_join(ylc_interpersonal_complete,ylc_communication_complete,by = c("Gender","Race","Major_Program","Organization","birth_year")) -> ylc_inter_com


ylc_inter_com



mod
mod <- "
f =~ q1.x + q2.x + q3.x + q4.x + q5.x + q6.x + q19.x + q20.x + q21.x + q31 + q32 + q33 + q1.y + q2.y + q3.y + q11.y + q12.y + q13.y + q17.y + q18.y + q19.y
relationships =~ q1.x + q2.x + q3.x + q4.x + q5.x + q6.x + q19.x + q20.x + q21.x + q31 + q32 + q33
communication =~ q1.y + q2.y + q3.y + q11.y + q12.y + q13.y + q17.y + q18.y + q19.y
f ~~ 1*f
"

ylc_inter_com -> comp_dat
cfa(mod,data = comp_dat, missing = "ml",std.lv = TRUE) %>% summary()

```

## Societal

```{r}

ylc_societal <- read_csv("data/slc-cr.csv", skip = 1)
colnames(ylc_societal) <- c("Progress","Gender","Race","Major_Program","Organization","birth_year","why_take_assessment",paste0("q",seq_along(8:25)))

ylc_societal %>% select(q1:q15) %>% cor(use = "p") %>% corrplot()

ylc_societal %>% na.omit() -> ylc_societal_complete

ylc_societal_two_factor_mod <- "
s_diversity =~ q1 + q2 + q3
s_others_circumstances =~ q4 + q5 + q6
s_diversity ~~ s_others_circumstances
s_others_circumstances ~~ 1*s_others_circumstances
s_diversity ~~ 1*s_diversity
"

ylc_societal_single_factor_mod <- "
f_societal =~ q9 + q10 + q11 + q12 + q13 + q14
f_societal ~~ 1*f_societal
"

ylc_societal_bifactor_mod <- "
f_blah =~ q7 + q8 + q9
f_societal =~ q1+ q2 + q3 + q4 + q5 + q6
s_diversity =~ q1+ q2 + q3
s_others_circumstances =~ q4 + q5 + q6
f_societal ~~ 1*f_societal
f_societal ~~ 0*s_diversity + 0*s_others_circumstances
f_blah ~~ 0*s_diversity + 0*s_others_circumstances
s_diversity ~~ 0*s_others_circumstances
f_blah ~~ f_societal
"

ylc_societal_complete %>% select(q9:q14) %>% factanal(factors = 2, rotation = "promax")
ylc_societal_complete %>% select(birth_year) %>% table()
cfa(ylc_societal_bifactor_mod, data = ylc_societal_complete, std.lv = TRUE) %>% {
    fit_societal <<- .
    fitMeasures(., c("cfi","rmsea","srmr"))
    }

summary(fit_societal, fit = TRUE)

semPaths(fit_societal, "std",title = TRUE, curvePivot = TRUE)
title("SLC-CR", line = 3)

"
diversity =~ q9 + q10 + q11
others_circumstances =~ q12 + q13 + q14
"
```

## Strategic

```{r}

"
research =~ q9 + q10 + q11
other_perspectives =~ q12 + q13 + q14
reflection_application =~ q15 + q16 + q17
analysis =~ q21 + q22 + q23
evaluation =~ q27 + q28 + q29
problem_solving =~ q33 + q34 + q35
decision_making =~ q36 + q37 + q38
"

```
> 
